"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var readline = require("readline");
var countryCodeToFullNameMap = {
    'AF': 'Afghanistan',
    'AL': 'Albania',
    'DZ': 'Algeria',
    'AD': 'Andorra',
    'AO': 'Angola',
    'AG': 'Antigua and Barbuda',
    'AR': 'Argentina',
    'AM': 'Armenia',
    'AU': 'Australia',
    'AT': 'Austria',
    'AZ': 'Azerbaijan',
    'BS': 'Bahamas',
    'BH': 'Bahrain',
    'BD': 'Bangladesh',
    'BB': 'Barbados',
    'BY': 'Belarus',
    'BE': 'Belgium',
    'BZ': 'Belize',
    'BJ': 'Benin',
    'BT': 'Bhutan',
    'BO': 'Bolivia',
    'BA': 'Bosnia and Herzegovina',
    'BW': 'Botswana',
    'BR': 'Brazil',
    'BN': 'Brunei',
    'BG': 'Bulgaria',
    'BF': 'Burkina Faso',
    'BI': 'Burundi',
    'KH': 'Cambodia',
    'CM': 'Cameroon',
    'CA': 'Canada',
    'CV': 'Cape Verde',
    'CF': 'Central African Republic',
    'TD': 'Chad',
    'CL': 'Chile',
    'CN': 'China',
    'CO': 'Colombia',
    'KM': 'Comoros',
    'CG': 'Congo (Brazzaville)',
    'CD': 'Congo (Kinshasa)',
    'CR': 'Costa Rica',
    'CI': 'Côte d Ivoire',
    'HR': 'Croatia',
    'CU': 'Cuba',
    'CY': 'Cyprus',
    'CZ': 'Czechia',
    'DK': 'Denmark',
    'DJ': 'Djibouti',
    'DM': 'Dominica',
    'DO': 'Dominican Republic',
    'EC': 'Ecuador',
    'EG': 'Egypt',
    'SV': 'El Salvador',
    'GQ': 'Equatorial Guinea',
    'ER': 'Eritrea',
    'EE': 'Estonia',
    'SZ': 'Eswatini',
    'ET': 'Ethiopia',
    'FJ': 'Fiji',
    'FI': 'Finland',
    'FR': 'France',
    'GA': 'Gabon',
    'GM': 'Gambia',
    'GE': 'Georgia',
    'DE': 'Germany',
    'GH': 'Ghana',
    'GR': 'Greece',
    'GD': 'Grenada',
    'GT': 'Guatemala',
    'GN': 'Guinea',
    'GW': 'Guinea-Bissau',
    'GY': 'Guyana',
    'HT': 'Haiti',
    'HN': 'Honduras',
    'HU': 'Hungary',
    'IS': 'Iceland',
    'IN': 'India',
    'ID': 'Indonesia',
    'IR': 'Iran',
    'IQ': 'Iraq',
    'IE': 'Ireland',
    'IL': 'Israel',
    'IT': 'Italy',
    'JM': 'Jamaica',
    'JP': 'Japan',
    'JO': 'Jordan',
    'KZ': 'Kazakhstan',
    'KE': 'Kenya',
    'KI': 'Kiribati',
    'KR': 'Korea (South)',
    'KW': 'Kuwait',
    'KG': 'Kyrgyzstan',
    'LA': 'Laos',
    'LV': 'Latvia',
    'LB': 'Lebanon',
    'LS': 'Lesotho',
    'LR': 'Liberia',
    'LY': 'Libya',
    'LI': 'Liechtenstein',
    'LT': 'Lithuania',
    'LU': 'Luxembourg',
    'MG': 'Madagascar',
    'MW': 'Malawi',
    'MY': 'Malaysia',
    'MV': 'Maldives',
    'ML': 'Mali',
    'MT': 'Malta',
    'MH': 'Marshall Islands',
    'MR': 'Mauritania',
    'MU': 'Mauritius',
    'MX': 'Mexico',
    'FM': 'Micronesia',
    'MD': 'Moldova',
    'MC': 'Monaco',
    'MN': 'Mongolia',
    'ME': 'Montenegro',
    'MA': 'Morocco',
    'MZ': 'Mozambique',
    'MM': 'Myanmar',
    'NA': 'Namibia',
    'NR': 'Nauru',
    'NP': 'Nepal',
    'NL': 'Netherlands',
    'NZ': 'New Zealand',
    'NI': 'Nicaragua',
    'NE': 'Niger',
    'NG': 'Nigeria',
    'NO': 'Norway',
    'OM': 'Oman',
    'PK': 'Pakistan',
    'PW': 'Palau',
    'PS': 'Palestine',
    'PA': 'Panama',
    'PG': 'Papua New Guinea',
    'PY': 'Paraguay',
    'PE': 'Peru',
    'PH': 'Philippines',
    'PL': 'Poland',
    'PT': 'Portugal',
    'QA': 'Qatar',
    'RO': 'Romania',
    'RU': 'Russia',
    'RW': 'Rwanda',
    'KN': 'Saint Kitts and Nevis',
    'LC': 'Saint Lucia',
    'VC': 'Saint Vincent and the Grenadines',
    'WS': 'Samoa',
    'SM': 'San Marino',
    'ST': 'São Tomé and Príncipe',
    'SA': 'Saudi Arabia',
    'SN': 'Senegal',
    'RS': 'Serbia',
    'SC': 'Seychelles',
    'SL': 'Sierra Leone',
    'SG': 'Singapore',
    'SK': 'Slovakia',
    'SI': 'Slovenia',
    'SB': 'Solomon Islands',
    'SO': 'Somalia',
    'ZA': 'South Africa',
    'ES': 'Spain',
    'LK': 'Sri Lanka',
    'SD': 'Sudan',
    'SR': 'Suriname',
    'SE': 'Sweden',
    'CH': 'Switzerland',
    'SY': 'Syria',
    'TW': 'Taiwan',
    'TJ': 'Tajikistan',
    'TZ': 'Tanzania',
    'TH': 'Thailand',
    'TL': 'Timor-Leste',
    'TG': 'Togo',
    'TO': 'Tonga',
    'TT': 'Trinidad and Tobago',
    'TN': 'Tunisia',
    'TR': 'Turkey',
    'TM': 'Turkmenistan',
    'TV': 'Tuvalu',
    'UG': 'Uganda',
    'UA': 'Ukraine',
    'AE': 'United Arab Emirates',
    'GB': 'United Kingdom',
    'US': 'United States',
    'UY': 'Uruguay',
    'UZ': 'Uzbekistan',
    'VU': 'Vanuatu',
    'VE': 'Venezuela',
    'VN': 'Vietnam',
    'YE': 'Yemen',
    'ZM': 'Zambia',
    'ZW': 'Zimbabwe',
};
var countryAdjacencyMap = {
    "AF": ["IR", "PK", "TM", "UZ", "TJ", "CN"],
    "AL": ["ME", "KS", "MK", "GR"],
    "DZ": ["TN", "LY", "NE", "ML", "MR", "EH", "MA"],
    "AD": ["FR", "ES"],
    "AO": ["NA", "ZM", "CD"],
    "AG": [],
    "AR": ["CL", "BO", "PY", "BR", "UY"],
    "AM": ["GE", "TR", "IR", "AZ"],
    "AU": [],
    "AT": ["DE", "CZ", "SK", "HU", "SI", "IT", "CH", "LI"],
    "AZ": ["RU", "GE", "AM", "IR"],
    "BS": [],
    "BD": ["IN", "MM"],
    "BB": [],
    "BY": ["RU", "UA", "PL", "LT", "LV"],
    "BE": ["NL", "DE", "LU", "FR"],
    "BZ": ["MX", "GT"],
    "BJ": ["BF", "NE", "NG", "TG"],
    "BT": ["IN", "CN"],
    "BO": ["BR", "PY", "AR", "CL", "PE"],
    "BA": ["HR", "ME", "RS"],
    "BW": ["NA", "ZW", "ZA", "ZM"],
    "BR": ["AR", "BO", "CO", "GY", "PY", "PE", "SR", "UY", "VE"],
    "BN": ["MY"],
    "BG": ["RO", "RS", "MK", "GR", "TR"],
    "BF": ["ML", "NE", "BJ", "TG", "GH", "CI"],
    "BI": ["RW", "TZ", "CD"],
    "KH": ["TH", "VN", "LA"],
    "CM": ["NG", "TD", "CF", "GQ", "GA", "CG"],
    "CA": ["US"],
    "CV": [],
    "CF": ["TD", "SD", "SS", "CD", "CG", "CM"],
    "TD": ["LY", "SD", "CF", "CM", "NG", "NE"],
    "CL": ["PE", "BO", "AR"],
    "CN": ["RU", "MN", "KP", "VN", "LA", "MM", "IN", "BT", "NP", "PK", "AF", "TJ", "KG", "KZ"],
    "CO": ["PA", "VE", "BR", "PE", "EC"],
    "KM": [],
    "CG": ["GA", "CM", "CF", "CD", "AO"],
    "CD": ["CG", "CF", "SS", "UG", "RW", "BI", "TZ", "ZM", "AO"],
    "CR": ["NI", "PA"],
    "CI": ["LR", "GN", "ML", "BF", "GH"],
    "HR": ["SI", "HU", "RS", "BA", "ME"],
    "CU": [],
    "CY": [],
    "CZ": ["DE", "PL", "SK", "AT"],
    "DK": ["DE"],
    "DJ": ["ER", "ET", "SO"],
    "DM": [],
    "DO": ["HT"],
    "EC": ["CO", "PE"],
    "EG": ["LY", "SD", "IL"],
    "SV": ["GT", "HN"],
    "GQ": ["CM", "GA"],
    "ER": ["SD", "ET", "DJ"],
    "EE": ["LV", "RU"],
    "SZ": ["ZA", "MZ"],
    "ET": ["ER", "DJ", "SO", "KE", "SS", "SD"],
    "FJ": [],
    "FI": ["SE", "NO", "RU"],
    "FR": ["BE", "LU", "DE", "CH", "IT", "ES", "AD", "MC"],
    "GA": ["GQ", "CM", "CG"],
    "GM": ["SN"],
    "GE": ["RU", "TR", "AM", "AZ"],
    "DE": ["NL", "BE", "LU", "FR", "CH", "AT", "CZ", "PL", "DK"],
    "GH": ["CI", "BF", "TG"],
    "GR": ["AL", "MK", "BG", "TR"],
    "GD": [],
    "GT": ["MX", "BZ", "HN", "SV"],
    "GN": ["GW", "SN", "ML", "SL", "LR", "CI"],
    "GW": ["SN", "GN"],
    "GY": ["VE", "BR", "SR"],
    "HT": ["DO"],
    "HN": ["GT", "SV", "NI"],
    "HU": ["SK", "UA", "RO", "RS", "HR", "SI", "AT"],
    "IS": [],
    "IN": ["PK", "CN", "NP", "BT", "BD", "MM"],
    "ID": ["PG", "TL", "MY"],
    "IR": ["AM", "AZ", "TM", "AF", "PK", "TR", "IQ"],
    "IQ": ["TR", "SY", "JO", "SA", "KW", "IR"],
    "IE": ["GB"],
    "IL": ["EG", "JO", "SY", "LB"],
    "IT": ["FR", "CH", "AT", "SI"],
    "JM": [],
    "JP": [],
    "JO": ["SY", "IQ", "SA", "IL"],
    "KZ": ["RU", "CN", "KG", "UZ", "TM"],
    "KE": ["UG", "SD", "ET", "SO", "TZ"],
    "KI": [],
    "KR": ["KP"],
    "KW": ["IQ", "SA"],
    "KG": ["KZ", "UZ", "TJ", "CN"],
    "LA": ["CN", "VN", "KH", "TH", "MM"],
    "LV": ["EE", "LT", "RU", "BY"],
    "LB": ["SY", "IL"],
    "LS": ["ZA"],
    "LR": ["GN", "CI", "SL"],
    "LY": ["TN", "DZ", "NE", "TD", "SD", "EG"],
    "LI": ["CH", "AT"],
    "LT": ["LV", "BY", "PL"],
    "LU": ["BE", "DE", "FR"],
    "MG": [],
    "MW": ["ZM", "TZ", "MZ"],
    "MY": ["TH", "BN", "ID"],
    "MV": [],
    "ML": ["MR", "DZ", "NE", "BF", "CI", "GN", "SN"],
    "MT": [],
    "MH": [],
    "MR": ["EH", "DZ", "ML", "SN"],
    "MU": [],
    "MX": ["US", "GT", "BZ"],
    "FM": [],
    "MD": ["UA", "RO"],
    "MC": ["FR"],
    "MN": ["RU", "CN"],
    "ME": ["HR", "BA", "RS", "KS", "AL"],
    "MA": ["DZ", "EH"],
    "MZ": ["TZ", "MW", "ZM", "ZW", "ZA", "SZ"],
    "MM": ["IN", "CN", "BD", "LA", "TH"],
    "NA": ["AO", "ZM", "BW", "ZA"],
    "NR": [],
    "NP": ["IN", "CN"],
    "NL": ["BE", "DE"],
    "NZ": [],
    "NI": ["HN", "CR"],
    "NE": ["LY", "TD", "NG", "BJ", "BF", "ML", "DZ"],
    "NG": ["BJ", "NE", "TD", "CM"],
    "NO": ["SE", "FI", "RU"],
    "OM": ["AE", "SA", "YE"],
    "PK": ["IN", "AF", "IR", "CN"],
    "PW": [],
    "PS": ["IL", "EG", "JO"],
    "PA": ["CR", "CO"],
    "PG": ["ID"],
    "PY": ["BR", "AR", "BO"],
    "PE": ["EC", "CO", "BR", "BO", "CL"],
    "PH": [],
    "PL": ["DE", "CZ", "SK", "UA", "BY", "LT"],
    "PT": ["ES"],
    "QA": ["SA"],
    "RO": ["UA", "MD", "HU", "RS", "BG"],
    "RU": ["NO", "FI", "EE", "LV", "LT", "PL", "BY", "UA", "GE", "AZ", "KZ", "CN", "MN", "KP"],
    "RW": ["UG", "TZ", "BI", "CD"],
    "KN": [],
    "LC": [],
    "VC": [],
    "WS": [],
    "SM": ["IT"],
    "ST": [],
    "SA": ["JO", "IQ", "KW", "QA", "AE", "OM", "YE"],
    "SN": ["MR", "ML", "GN", "GW", "GM"],
    "RS": ["HU", "RO", "BG", "MK", "AL", "ME", "BA", "HR"],
    "SC": [],
    "SL": ["GN", "LR"],
    "SG": ["MY"],
    "SK": ["CZ", "PL", "UA", "HU", "AT"],
    "SI": ["IT", "AT", "HU", "HR"],
    "SB": [],
    "SO": ["ET", "KE", "DJ"],
    "ZA": ["NA", "BW", "ZW", "MZ", "SZ", "LS"],
    "ES": ["FR", "AD", "PT", "GB"],
    "LK": [],
    "SD": ["EG", "LY", "TD", "CF", "SS", "ER"],
    "SR": ["GY", "BR", "GF"],
    "SE": ["NO", "FI"],
    "CH": ["DE", "FR", "IT", "AT", "LI"],
    "SY": ["TR", "IQ", "JO", "IL", "LB"],
    "TW": [],
    "TJ": ["UZ", "KG", "CN", "AF"],
    "TZ": ["KE", "UG", "RW", "BI", "ZM", "MW", "MZ"],
    "TH": ["MM", "LA", "KH", "MY"],
    "TL": ["ID"],
    "TG": ["GH", "BF", "BJ"],
    "TO": [],
    "TT": [],
    "TN": ["DZ", "LY"],
    "TR": ["GR", "BG", "GE", "AM", "AZ", "IR", "IQ", "SY"],
    "TM": ["IR", "AF", "UZ", "KZ"],
    "TV": [],
    "UG": ["SS", "KE", "TZ", "RW", "CD"],
    "UA": ["PL", "SK", "HU", "RO", "MD", "BY", "RU"],
    "AE": ["SA", "OM"],
    "GB": ["IE"],
    "US": ["CA", "MX"],
    "UY": ["BR", "AR"],
    "UZ": ["KZ", "KG", "TJ", "AF", "TM"],
    "VU": [],
    "VE": ["CO", "BR", "GY"],
    "VN": ["CN", "LA", "KH"],
    "YE": ["SA", "OM"],
    "ZM": ["TZ", "MW", "MZ", "ZW", "BW", "NA", "AO", "CD"],
    "ZW": ["ZM", "MZ", "ZA", "BW"]
};
function getFullCountryNameFromCode(countryCode) {
    var countryFullName = countryCodeToFullNameMap[countryCode];
    return countryFullName || 'Unknown Country';
}
function getAdjacentCountriesList(countryCode) {
    var adjacentCountryCodes = countryAdjacencyMap[countryCode] || [];
    return adjacentCountryCodes.map(function (code) { return getFullCountryNameFromCode(code); });
}
var inputInterface = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});
function initiateCountryLookup() {
    inputInterface.question('Enter a Country Code (e.g., IN/US/NZ) or "exit" to quit: ', function (userInput) {
        var countryCode = userInput.trim().toUpperCase();
        if (countryCode === 'EXIT') {
            console.log('Exiting the program...');
            inputInterface.close();
            return;
        }
        var countryFullName = getFullCountryNameFromCode(countryCode);
        if (countryFullName === 'Unknown Country') {
            console.log('Invalid country code entered!');
        }
        else {
            var adjacentCountries = getAdjacentCountriesList(countryCode);
            console.log("Country: ".concat(countryFullName));
            if (adjacentCountries.length === 0) {
                console.log('No adjacent countries found.');
            }
            else {
                console.log('Adjacent Countries:');
                adjacentCountries.forEach(function (country) { return console.log(country); });
            }
        }
        initiateCountryLookup();
    });
}
console.log('Welcome to the Country Lookup Program!');
console.log('You can enter a country code (e.g., IN for India) to get information about it.');
initiateCountryLookup();
